import Nav from "../components/Nav";import Connect from "../components/Connect";import { useState } from "react";
export default function Connections(){const[semrush,setSemrush]=useState("");const[surfer,setSurfer]=useState("");const[clarity,setClarity]=useState("");const[serpapi,setSerpapi]=useState("");
const saveKey=async(k:string,v:string)=>{const r=await fetch("/api/storage/kv/set",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:k,value:v})});const j=await r.json();if(!r.ok) alert(j.error||"Save failed"); else alert("Saved");};
return(<main><Nav/><div className="max-w-5xl mx-auto p-6 space-y-6"><h1 className="text-xl font-bold">Connections</h1><p className="text-sm text-gray-600">Google sign-in enables GA4, GSC, GBP, and Sheets. Other providers use API keys (encrypted, stored in your personal Sheet).</p>
<section className="grid md:grid-cols-2 gap-4">
  <div className="p-4 border rounded-lg space-y-3"><h3 className="font-medium">Google (GA4 / GSC / GBP / Sheets)</h3><Connect provider="google"/></div>
  <div className="p-4 border rounded-lg space-y-2"><h3 className="font-medium">SEMRush (API Key)</h3><input className="w-full border rounded p-2" value={semrush} onChange={e=>setSemrush(e.target.value)} placeholder="SEMRUSH_API_KEY"/><button className="px-3 py-2 rounded bg-black text-white" onClick={()=>saveKey("SEMRUSH_API_KEY",semrush)}>Save</button></div>
  <div className="p-4 border rounded-lg space-y-2"><h3 className="font-medium">Surfer SEO (API Key)</h3><input className="w-full border rounded p-2" value={surfer} onChange={e=>setSurfer(e.target.value)} placeholder="SURFER_API_KEY"/><button className="px-3 py-2 rounded bg-black text-white" onClick={()=>saveKey("SURFER_API_KEY",surfer)}>Save</button></div>
  <div className="p-4 border rounded-lg space-y-2"><h3 className="font-medium">Microsoft Clarity (Project API Key)</h3><input className="w-full border rounded p-2" value={clarity} onChange={e=>setClarity(e.target.value)} placeholder="CLARITY_API_KEY"/><button className="px-3 py-2 rounded bg-black text-white" onClick={()=>saveKey("CLARITY_API_KEY",clarity)}>Save</button></div>
  <div className="p-4 border rounded-lg space-y-2"><h3 className="font-medium">SERP lookups (SerpAPI)</h3><input className="w-full border rounded p-2" value={serpapi} onChange={e=>setSerpapi(e.target.value)} placeholder="SERPAPI_KEY"/><button className="px-3 py-2 rounded bg-black text-white" onClick={()=>saveKey("SERPAPI_KEY",serpapi)}>Save</button></div>
</section></div></main>);}